// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFV2YfJzWGYUqzU5DvP5LwcAkDBuyduA',
    appId: '1:1066573293903:web:912d9db4ca540dea3a7d3a',
    messagingSenderId: '1066573293903',
    projectId: 'app-asher-fixit',
    authDomain: 'app-asher-fixit.firebaseapp.com',
    storageBucket: 'app-asher-fixit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjxGN990C5xOgyE-0SpronHJwPmhUYOrA',
    appId: '1:1066573293903:android:aeb0eac8cb4893073a7d3a',
    messagingSenderId: '1066573293903',
    projectId: 'app-asher-fixit',
    storageBucket: 'app-asher-fixit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4-YjEQY51eaI_oQm1s7VFlkYgeNtZy_g',
    appId: '1:1066573293903:ios:9bbde8abeee20f913a7d3a',
    messagingSenderId: '1066573293903',
    projectId: 'app-asher-fixit',
    storageBucket: 'app-asher-fixit.firebasestorage.app',
    iosBundleId: 'app.asher.fixit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4-YjEQY51eaI_oQm1s7VFlkYgeNtZy_g',
    appId: '1:1066573293903:ios:9bbde8abeee20f913a7d3a',
    messagingSenderId: '1066573293903',
    projectId: 'app-asher-fixit',
    storageBucket: 'app-asher-fixit.firebasestorage.app',
    iosBundleId: 'app.asher.fixit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwFV2YfJzWGYUqzU5DvP5LwcAkDBuyduA',
    appId: '1:1066573293903:web:d334a2be9b142d7f3a7d3a',
    messagingSenderId: '1066573293903',
    projectId: 'app-asher-fixit',
    authDomain: 'app-asher-fixit.firebaseapp.com',
    storageBucket: 'app-asher-fixit.firebasestorage.app',
  );
}
